#!/bin/bash
#SBATCH -J gpu_test
## SBATCH -n 1
#SBATCH -N 1                    # Ensure that all cores are on one machine
#SBATCH -t 2-00:05              # Runtime in D-HH:MM
#SBATCH --nodelist=gpu
#SBATCH --partition GPU
#SBATCH --mem=5000

srun -l /bin/hostname

###### Step 0: Define the code directory ######
code_dir=. # e.g. ~/workspace/FACT-AI-2023/Label-Free-XAI

###### Step 1: Load all necessary modules ######
module use /share/apps/eb/modules/all
module load CUDA/11.1.1-GCC-10.2.0
# module load CUDA
module load cuDNN/8.0.5.39-CUDA-11.1.1

###### Step 2: Make sure to deactivate any conda environments ######
# conda deactivate

###### Step 2: Create a virtual environment with name env ######
python -m venv env

###### Step 3: Activate the virtual environment ######
source $code_dir/env/bin/activate

###### Step 4: Install the required libraries package libraries ######
$code_dir/env/bin/pip install .

source cuda11.1
# To see Cuda version in use
# nvcc -V
# $code_dir/env/bin/pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

# ###### Step 8: Move to the experiments folder ######
cd $code_dir/experiments
nvidia-smi
# MNIST experiments
# python -m mnist --name consistency_features
# python -m mnist --name consistency_examples
# python -m mnist --name roar_test
# python -m mnist --name pretext
# python -m mnist --name disvae

# ECG5000 experiments
# python -m ecg5000 --name consistency_features
# python -m ecg5000 --name consistency_examples

# CIFAR10 experiments
# python -m cifar10 --name consistency_features
# python -m cifar10 --name consistency_examples

# dSprites experiment
# python -m dsprites